### ISSUE TITLE
Maybe some features to add! 

### ISSUE THREAD

**Issue by thewipal** [InitialDet/MyDalamudPlugins#1]
1.) First one would be to use cordials after certain fish? like, say i catch a hammer head and I'm able to command it to use cordials after hammer head is captured so i maybe have enough to use triple hook! 

and after identical cast is activated there is no timer for it to expire! so there could be an option to "wait until gp is this full" before casting again!! :D

THANKS SOO MUCH FOR THIS ADD ON <3  It helped me complete my fishing relic while doing homework!! <3 me and my friends go on fishing boats now for scripts and stuff and use ur program, have an awesome dayy

**Comment by InitialDet** [comment]
I'll try to include this feature in the next few updates o/
